encoding: UTF-8

highlighter: pygments
# paginate: 8
permalink: /:title

markdown: rdiscount

title: 生龙活虎
nickname: 陈生龙
url: http://wenin819.com
img_url: http://wenin819.com

author: 哲曦
email: shenglong.csl@gmail.com
