encoding: UTF-8

highlighter: pygments
# paginate: 8
permalink: /:title

markdown: rdiscount

title: 生龙活虎
nickname: 陈生龙
url: http://shenglongcsl.io
img_url: http://shenglongcsl.io

author: 哲曦
email: shenglong.csl@gmail.com
